### PR TITLE
update npm dependencies

### PR DESCRIPTION
**Pull request by riesendaniel**
im .env.local muss noch folgende Zeile hinzugüefügt werden:
SKIP_PREFLIGHT_CHECK=true

### CODE REVIEW

**Comment by riesendaniel** [comment]
Console-Error 
Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.

**Comment by riesendaniel** [comment]
Console-Error 2
Warning: Failed prop type: The prop `numeric` of `TableCell` is deprecated. Instead, use the `align` property.
    in TableCell (created by WithStyles(TableCell))
    in WithStyles(TableCell) (created by WithStyles(WithStyles(TableCell)))
    in WithStyles(WithStyles(TableCell)) (at ResponsiveTable.jsx:165)
    in ResponsiveTableCell (at BudgetListComponent.jsx:33)
    in tr (created by Context.Consumer)
    in TableRow (created by WithStyles(TableRow))
    in WithStyles(TableRow) (created by WithStyles(WithStyles(TableRow)))
    in WithStyles(WithStyles(TableRow)) (at ResponsiveTable.jsx:138)
    in ResponsiveTableRow (at BudgetListComponent.jsx:29)
    in thead (created by TableHead)
    in TableHead (created by WithStyles(TableHead))
    in WithStyles(TableHead) (created by WithStyles(WithStyles(TableHead)))
    in WithStyles(WithStyles(TableHead)) (at ResponsiveTable.jsx:62)
    in ResponsiveTableHead (at BudgetListComponent.jsx:28)
    in table (created by Table)
    in Table (created by WithStyles(Table))
    in WithStyles(Table) (created by WithStyles(WithStyles(Table)))
    in WithStyles(WithStyles(Table)) (at ResponsiveTable.jsx:41)
    in div (created by Grid)
    in Grid (created by WithStyles(Grid))
    in WithStyles(Grid) (at ResponsiveTable.jsx:40)
    in ResponsiveTable (at BudgetListComponent.jsx:27)
    in div (created by CardContent)
    in CardContent (created by WithStyles(CardContent))
    in WithStyles(CardContent) (at BudgetListComponent.jsx:25)
    in div (created by Paper)
    in Paper (created by WithStyles(Paper))
    in WithStyles(Paper) (created by Card)
    in Card (created by WithStyles(Card))
    in WithStyles(Card) (at BudgetListComponent.jsx:19)
    in BudgetListComponent (at BudgetComponent.jsx:90)
    in div (created by Grid)
    in Grid (created by WithStyles(Grid))
    in WithStyles(Grid) (at BudgetComponent.jsx:89)
    in div (created by Grid)
    in Grid (created by WithStyles(Grid))
    in WithStyles(Grid) (at BudgetComponent.jsx:85)
    in div (at BudgetComponent.jsx:84)
    in div (created by Grid)
    in Grid (created by WithStyles(Grid))
    in WithStyles(Grid) (at BudgetComponent.jsx:82)
    in div (created by Grid)
    in Grid (created by WithStyles(Grid))
    in WithStyles(Grid) (at BudgetComponent.jsx:78)
    in div (at BudgetComponent.jsx:77)
    in BudgetComponent (created by WithStyles(BudgetComponent))
    in WithStyles(BudgetComponent) (created by Context.Consumer)
    in Connect(WithStyles(BudgetComponent)) (created by Route)
    in Route (at AppComponent.jsx:181)
    in Switch (at AppComponent.jsx:179)
    in main (at AppComponent.jsx:178)
    in div (at AppComponent.jsx:175)
    in div (at AppComponent.jsx:168)
    in Router (at AppComponent.jsx:167)
    in div (at AppComponent.jsx:166)
    in AppComponent (created by WithStyles(AppComponent))
    in WithStyles(AppComponent) (created by Context.Consumer)
    in Connect(WithStyles(AppComponent)) (created by WithWidth(Connect(WithStyles(AppComponent))))
    in WithWidth(Connect(WithStyles(AppComponent))) (created by WithTheme(WithWidth(Connect(WithStyles(AppComponent)))))
    in WithTheme(WithWidth(Connect(WithStyles(AppComponent)))) (at src/index.js:18)
    in MuiThemeProviderOld (at src/index.js:17)
    in Provider (at src/index.js:16)
function.console.(anonymous function) @ index.js:1446
printWarning @ checkPropTypes.js:20
checkPropTypes @ checkPropTypes.js:75
validatePropTypes @ react.development.js:1717
createElementWithValidation @ react.development.js:1810
render @ withStyles.js:337
finishClassComponent @ react-dom.development.js:15141
updateClassComponent @ react-dom.development.js:15096
beginWork @ react-dom.development.js:15980
performUnitOfWork @ react-dom.development.js:19102
workLoop @ react-dom.development.js:19143
renderRoot @ react-dom.development.js:19228
performWorkOnRoot @ react-dom.development.js:20165
performWork @ react-dom.development.js:20075
performSyncWork @ react-dom.development.js:20049
interactiveUpdates$1 @ react-dom.development.js:20337
interactiveUpdates @ react-dom.development.js:2267
dispatchInteractiveEvent @ react-dom.development.js:5083

**Comment by riesendaniel** [comment]
im .env.local muss noch folgende Zeile hinzugüefügt werden:
SKIP_PREFLIGHT_CHECK=true

**Comment by sarner** [comment]
Ist die `browserslist`-Konfiguration für Babel?

**Comment by sarner** [comment]
Für was ist die neue Konfiguration `SKIP_PREFLIGHT_CHECK=true`?

**Comment by sarner** [comment]
Um den zweiten Konsolefehler kann ich mich sonst kümmern...

**Comment by riesendaniel** [comment]
> Um den zweiten Konsolefehler kann ich mich sonst kümmern...

wenn du gerade weisst wie gerne.

das mit den browser kam von hier:
As of react-scripts >=2 you must specify targeted browsers.


und das mit den skip ist durch das reingekommen: was meinst du hier, wollen wir das noch anpassen oder den skip drin lassen?
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "eslint": "5.6.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of eslint was detected higher up in the tree:

  C:\Users\Daniel\repos\myFinanceTracker\node_modules\eslint (version: 5.11.1)

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "eslint" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if C:\Users\Daniel\repos\myFinanceTracker\node_modules\eslint is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls eslint in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed eslint.

If nothing else helps, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That would permanently disable this preflight check in case you want to proceed anyway.

**Comment by sarner** [comment]
Hast du die vorgeschlagenen Schritte bereits versucht?

**Comment by riesendaniel** [comment]
doch das geht schon so, wollen wir das so machen? dann braucht es das im env.local nicht mehr.
Dazu musst du bei dir package-lock.json und yarn.lock löschen
Anschliessend die node_modules
danach wieder npm i durchführen und es sollte laufen.

**Comment by sarner** [comment]
> doch das geht schon so, wollen wir das so machen? dann braucht es das im env.local nicht mehr.
> Dazu musst du bei dir package-lock.json und yarn.lock löschen
> Anschliessend die node_modules
> danach wieder npm i durchführen und es sollte laufen.

Diese Lösung passt so für mich. Kannst du deine neuen package-lock.json und yarn.lock commiten und anschliessend die Merge Conflicts bereinigen?

**Comment by riesendaniel** [comment]
ist alles drin

**Pull request merged**
